<a href="https://colab.research.google.com/github/keerthiroshan005/Pandas-Numpy/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install numpy


In [ ]:
pip  install pandas

In [ ]:
pip install scikit-learn

In [ ]:
import numpy as np
arr=np.array([10,20,30,40,50])
print(arr)

[10 20 30 40 50]


In [ ]:
import numpy as np
arr=np.array([100,400,50,90,1000])
np.max(arr)

np.int64(1000)

In [ ]:
import numpy as np
import pandas as pd
df=pd.DataFrame({"Marks":[80,90,78]})
np.sum(df)

/usr/local/lib/python3.12/dist-packages/numpy/_core/fromnumeric.py:84: FutureWarning: The behavior of DataFrame.sum with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)


,0
Marks,248


### Age Checker

This code will ask for your name and age, then check if your age is above 18. If it is, it will display your name and age.

In [ ]:
import pandas as pd
df=pd.DataFrame({"Name":["Keerthi","mohan","Roshan","priya"],
                 "Age":[20,15,17,18]})

adults_df = df[df['Age'] > 18]
print(adults_df)

      Name  Age
0  Keerthi   20


### Create and Display Data from CSV

In [ ]:
data=pd.read_csv("/File.csv")
print(data.head(5))

      Monday
0    Tuesday
1  Wednesday
2   Thursday
3     Friday
4   Saturday


In [ ]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

data={"election_hours":[8,5,12,10],"No of booths":[54016,45678,1345,7880],"result":[0,0,1,1,]}
df=pd.DataFrame(data)
x=df[["election_hours"]]
y=df["result"]
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=50,test_size=0.3)
model=LogisticRegression()
model.fit(x_train,y_train)
y_pred=model.predict(x_test)
accuracy=accuracy_score(y_test,y_pred)
print(accuracy)

1.0


In [ ]:
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

data={"election_hours":[8,5,12,10],"No of booths":[54016,45678,1345,7880],"result":[0,0,1,1,]}
df=pd.DataFrame(data)
x=df[["election_hours"]]
y=df["result"]
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=50,test_size=0.3)
model=LinearRegression()
model.fit(x_train,y_train)
y_pred=model.predict(x_test)
mse=mean_squared_error(y_test,y_pred)

print(f"Mean Squared Error:{mse}")

Mean Squared Error:1.6249999999999984


In [ ]:
from sklearn.cluster import KMeans
x=[[35],[40],[18],[80],[85],[90]]
model=KMeans(n_clusters=2)
model.fit(x)
print(model.labels_)

[0 0 0 1 1 1]


In [ ]:
from sklearn.cluster import AgglomerativeClustering
x=[[35],[40],[70],[80],[85],[45]]
model=AgglomerativeClustering(n_clusters=2)
model.fit(x)
print(model.labels_)

[1 1 0 0 0 1]


In [ ]:
from sklearn.cluster import DBSCAN
x=[[35],[40],[90],[80],[85],[45]]
model = DBSCAN(eps=5, min_samples=2)
model.fit(x)
print(model.labels_)

[0 0 1 1 1 0]


In [ ]:
from sklearn.decomposition import PCA
x=[[35],[40],[90],[80],[85],[45]]

pca = PCA(n_components=1) # Reducing to 1 principal component
pca.fit(x)
x_pca = pca.transform(x)

print("Original data:\n", x)
print("Transformed data (PCA):\n", x_pca)
print("Explained variance ratio (first component):", pca.explained_variance_ratio_)

Original data:
 [[35], [40], [90], [80], [85], [45]]
Transformed data (PCA):
 [[-27.5]
 [-22.5]
 [ 27.5]
 [ 17.5]
 [ 22.5]
 [-17.5]]
Explained variance ratio (first component): [1.]
